app.py
from flask import Flask, render_template
from views import my_view

app = Flask(__name__) 

app.register_blueprint(my_view)

# @app.errorhandler(404)
# def page_not_found(e):
#     return render_template("404.html", e=e)


if __name__=="__main__":
    app.run(debug=True, port=8000)

views.py
from flask import render_template, redirect, url_for, Blueprint, request
# from app import app

my_view = Blueprint('my_view', __name__)

@my_view.route("/")    
def home():
    return render_template('index.html')

@my_view.route("/about")    
def about():
    return render_template('about.html')

@my_view.route("/rosaria")   # when the url is our_app/contact
def rosaria():
    return render_template('rosaria.html') #return contact.html

templates/about.html
{% extends 'base.html' %}
{% block content %}
hi I'm katy
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum veniam deleniti eligendi, placeat inventore suscipit illum illo quo, sed quam ratione pariatur sit adipisci expedita voluptatibus odio commodi dolor praesentium doloremque quas. Atque unde sequi ipsam quos corrupti iusto impedit recusandae, quae earum magnam quod repellendus consectetur, possimus laborum cumque minima ut optio exercitationem totam. Porro adipisci accusamus illo optio rerum magni fugit inventore ullam aliquam quis, tempore autem consequuntur quibusdam pariatur quod sunt ut blanditiis deleniti similique qui voluptas dicta! Ullam rerum harum, repellat natus impedit veritatis ipsam beatae doloribus quidem architecto cupiditate velit deserunt porro vitae atque. Officiis!</p>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <link rel="stylesheet" href="{{url_for('static', filename = 'style.css')}}"> 
    <title>UglyImpact</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">UglyImpact</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('my_view.home')}}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('my_view.about')}}">About Me</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <div class="container">
      <h1>Welcome to My</h1>
      <h1>Genshin Impact Profile</h1>
      <hr>
        {% block content %}
        {% endblock %}
    </div>
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="charbox">
    <div class="card hydro"><b>Xingqiu</b>
        <img src="{{url_for('static', filename = 'imgs/xing.png')}}" class="profile">
        <ul>
            <li>Level: 90</li>
            <li> Talents: 8 9 9</li>
            <li> Role:Sub-DPS</li>
            <li> Weapon: Sacrifical Sword</li>
            <li>Set: Severed Fate</li>
            <li>Notes: Support loadout for Kazuha &lt;-&gt; Diona swap</li>
    </ul></div>
    <div class="card cryo"><b>Diona</b>
        <img src="{{url_for('static', filename = 'imgs/diona.png')}}" class="profile">
        <ul>
            <li>Level: 90</li>
            <li> Talents: 4 8 8</li>
            <li> Role: Support</li>
            <li> Weapon: Sacrifical Bow</li>
            <li>Set: Tenacity</li>
            <li>Notes: Build full HP</li>
        </ul>
    </div>
    <div class="card electro"><b>Fischl</b>
        <img src="{{url_for('static', filename = 'imgs/fischl.png')}}" class="profile">
        <ul>
            <li>Level: 90</li>
            <li> Talents: 8 13 13</li>
            <li> Role: Sub-DPS</li>
            <li> Weapon: Stringless</li>
            <li>Set: Thundering Fury</li>
            <li>Notes:</li>
        </ul>
    </div>
    <div class="card cryo"><b>Rosaria</b>
        <img src="{{url_for('static', filename = 'imgs/rosaria.png')}}" class="profile">
        <ul>
            <li>Level: 90</li>
            <li> Talents: 8 13 12</li>
            <li> Role: Main-DPS</li>
            <li> Weapon:Deathmatch</li>
            <li>Set:Blizzard Strayer</li>
            <li>Notes: Physical loadout for cryo enimies</li>
        </ul>
    </div>
{% endblock %}